project_id = "pwdkfekouyyujfwmgqls"

[functions.student-auth]
verify_jwt = false

[functions.send-n8n-webhook]
verify_jwt = false

[functions.provision-coordinator-auth]
verify_jwt = false

[functions.enem-config]
verify_jwt = true

[functions.enem-corrigir]
verify_jwt = true

[functions.gerar-tema]
verify_jwt = true

[functions.gerar-redacao-modelo]
verify_jwt = true

[functions.gerar-tema-webhook]
verify_jwt = false

[functions.salvar-redacao]
verify_jwt = false