// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwdkfekouyyujfwmgqls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3ZGtmZWtvdXl5dWpmd21ncWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1Mjc4OTQsImV4cCI6MjA2ODEwMzg5NH0.FQfRU7zv5Y2cj2CZT6KFdciekApZl8NxThZjfTNLzko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});